### ISSUE TITLE
quality selector button not showing

### ISSUE THREAD

**Issue by SolmazKh** [silvermine/videojs-quality-selector#15]
Hello
My code:

`var vjs_input = {
        "controls": true, "autoplay": auto_play, "muted": false, "plugins": vjs_plugins,"qualitySelector": true
    };
 videojs("video_elem", vjs_input).ready(function () {
...
}`

Why the button is not added?

**Comment by billpendrydotcom** [comment]
I was having the same issue. There is CSS that must be included, which is not mentioned in the instructions. The CSS is in SCSS format, which I'm not clever enough to be using, lol.

1. Grab this file: videojs-quality-selector/src/sass/quality-selector.scss
2. Then convert it to normal CSS. I found an online converter via Google.
3. Finally, just include the converted CSS, and you should be good to go!

**Comment by jthomerson** [comment]
Oh, wow, we missed this issue back in December. Sorry @SolmazKh! If your issue really is just the missing CSS, you can do as @billpendrydotcom says, or you can simply link to the CDN-hosted one, similar to how the JS example on the project homepage mentions. For example, you can link to https://unpkg.com/silvermine-videojs-quality-selector@1.1.2/dist/css/quality-selector.css

If someone wants to open a pull request to update the README to include CSS, you're welcome to do so.

**Comment by pilishen** [comment]
in my case, it was
`require('!style-loader!css-loader!silvermine-videojs-quality-selector/dist/css/quality-selector.css')`

using in a vue component
of course, u can also include within style tag

**Comment by jthomerson** [comment]
I believe #35 closed this.
