### ISSUE TITLE
Playback pauses after using quality selector in Safari 11

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-quality-selector#16]
In Safari 11, when changing the quality using the quality selector while a video is playing, playback does not resume after the change as it does in other players.

This is likely due to using the `loadeddata` event here: https://github.com/silvermine/videojs-quality-selector/blob/1f1f78b267958a64461975bfab80407117c0105e/src/js/index.js#L34

`loadeddata` is not fired after the source is updated in Safari. Additionally, if the [preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload) attribute is set to `none`, this likely will not work in any browser.

**Comment by onebytegone** [comment]
Closed by #17
