### ISSUE TITLE
Detect change

### ISSUE THREAD

**Issue by jalowin** [silvermine/videojs-quality-selector#20]
Is possible detect when the user change the quality for make do anything?

Thanks for all

Best regards

**Comment by onebytegone** [comment]
@jalowin Can you be more specific when you say "detect when the user changes the quality"? Do you mean as an [event](https://docs.videojs.com/tutorial-event-target.html)? If so, please see #23. There is a discussion there about events on quality change. If you are inquiring about something different, please feel free to elaborate and reopen this issue.
