### ISSUE TITLE
Event for video quality change

### ISSUE THREAD

**Issue by hack4mer** [silvermine/videojs-quality-selector#23]
I was trying to find an event that fires when video quality is changed and could not find any. Should I add a custom event for it in this plugin?  I can create a pull request with my event implementation.

or there is a way around?

**Comment by onebytegone** [comment]
@hack4mer Can you be more specific as to what you mean by "when video quality is changed"? (e.g. when the user selects the quality or when the actual source changes?)

There are already two events being triggered on the player when the quality "changes". The first is [`qualityRequested`](https://github.com/silvermine/videojs-quality-selector/blob/13535a8ca6a4e95de0478bb68cd8c9d6d7dd2f9e/src/js/events.js#L5) which occurs when the user [selects the resolution's MenuItem](https://github.com/silvermine/videojs-quality-selector/blob/13535a8ca6a4e95de0478bb68cd8c9d6d7dd2f9e/src/js/components/QualityOption.js#L42). The second is [`qualitySelected`](https://github.com/silvermine/videojs-quality-selector/blob/13535a8ca6a4e95de0478bb68cd8c9d6d7dd2f9e/src/js/events.js#L6) which occurs when the [middleware selects the proper source](https://github.com/silvermine/videojs-quality-selector/blob/13535a8ca6a4e95de0478bb68cd8c9d6d7dd2f9e/src/js/middleware/SourceInterceptor.js#L35). Both these events are [already being used](https://github.com/silvermine/videojs-quality-selector/blob/13535a8ca6a4e95de0478bb68cd8c9d6d7dd2f9e/src/js/components/QualitySelector.js#L27-L40) to ensure the selected resolution in the menu is correct.

**Comment by hack4mer** [comment]
Yes, my bad, thanks.
