### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by faridv** [silvermine/videojs-quality-selector#24]
I'm trying to use this plugin with the latest version of videojs but I can't make it work and it doesn't give me any error/notices. I tried the demo provided in the repo but it's not working either. Is this project still alive or not?

**Comment by jthomerson** [comment]
@faridv: Yes, the project is active and the plugin works with all versions that we've tested it with. If you'd like assistance, you will need to post a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve). Sometimes just by creating a MCVE you will actually discover the source of the problem yourself - or at least more details to help us reproduce it.

If you want some good examples of MCVE's, see a couple of issues that we have posted elsewhere, e.g:

 * https://github.com/videojs/video.js/issues/4765
 * https://github.com/videojs/http-streaming/issues/172

All of that detail is really important in getting help - especially on an open source plugin where people are donating their time. Without it we can't be sure what version of VideoJS you're using, or what other plugins you're using with it.

If you're able to reproduce the issue in an MVCE, post a comment here and the issue can be reopened.
