### ISSUE TITLE
I test index.html for demo but it dont't have any quility selector

### ISSUE THREAD

**Issue by hediehrafiee** [silvermine/videojs-quality-selector#37]
![Screenshot_2019-10-24 videojs-quality-selector Demo](https://user-images.githubusercontent.com/22467829/67492525-68bee380-f683-11e9-9962-0433f1d6fd5b.png)

**Comment by jthomerson** [comment]
@hediehrafiee: If you'd like assistance, you will need to post a minimal, complete, verifiable example. Sometimes just by creating a MCVE you will actually discover the source of the problem yourself - or at least more details to help us reproduce it.

If you want some good examples of MCVE's, see a couple of issues that we have posted elsewhere, e.g:

 * https://github.com/videojs/video.js/issues/4765
 * https://github.com/videojs/http-streaming/issues/172

All of that detail is really important in getting help - especially on an open source plugin where people are donating their time. Without it we can't be sure what version of VideoJS you're using, or what other plugins you're using with it.

If you're able to reproduce the issue in an MVCE, post a comment here and the issue can be reopened.
