### ISSUE TITLE
Error in demo example

### ISSUE THREAD

**Issue by EdoardoLopez** [silvermine/videojs-quality-selector#40]
I download library like zip, and open demo example but i have this error

`Uncaught Error: Component QualitySelector does not exist
    at ControlBar.addChild`

**Comment by jthomerson** [comment]
@EdoardoLopez Pull requests are welcome. Please make sure to read and comply with [our coding standards](https://github.com/silvermine/silvermine-info/blob/master/coding-standards.md) to ensure your PR has the best chance of success.

**Comment by yokuze** [comment]
@EdoardoLopez If you mean that you just downloaded this project from Github as a zip file, unzipped it, and then opened the demo page **without building the project first** then yes, you will see that error. The demo page depends on you having built the project locally.

Please run: 

```
npm install
./node_modules/.bin/grunt build
```

inside of the project first, and then open the demo page.

@jthomerson For the sake of thoroughness, I verified that the demo page is working as expected. I believe this ticket can be closed.
