### ISSUE TITLE
Where do I find unpkg link to version 1.2.3

### ISSUE THREAD

**Issue by DJ-PD** [silvermine/videojs-quality-selector#50]
Where do I find unpkg link to version 1.2.3?
https://unpkg.com/silvermine-videojs-quality-selector/dist/js/silvermine-videojs-quality-selector.min.js redirected to version 1.1.2

**Comment by yokuze** [comment]
@DJ-PD a few versions ago we moved this package over to the @silvermine scope, so the URL changed slightly: https://unpkg.com/@silvermine/videojs-quality-selector@1.2.3/dist/js/silvermine-videojs-quality-selector.min.js

**Comment by jthomerson** [comment]
Re-opening so we can update the README

**Comment by jthomerson** [comment]
Fixed in #51
