### ISSUE TITLE
issue with the "selected" value

### ISSUE THREAD

**Issue by snakeeater4526** [silvermine/videojs-quality-selector#54]
i made a page with multiple video on the same page
but when i trigger the "selected=true", the only video it was load is the one with this value
and no others video on the page

if i miss somethings, sorry

but for me it's a real problem

sorry i'm french, i try my best for this strange thing^^
![Annotation 2020-01-02 211605](https://user-images.githubusercontent.com/41698614/71690690-b5225000-2da5-11ea-9159-510a7a3127ad.png)

**Comment by jthomerson** [comment]
@snakeeater4526: If you'd like assistance, you will need to post a minimal, complete, verifiable example. (MCVE) Sometimes just by creating a MCVE you will actually discover the source of the problem yourself - or at least more details to help us reproduce it.

If you want some good examples of MCVE's, see a couple of issues that we have posted elsewhere, e.g:

 * https://github.com/videojs/video.js/issues/4765
 * https://github.com/videojs/http-streaming/issues/172

All of that detail is really important in getting help - especially on an open source plugin where people are donating their time. Without it we can't be sure what version of VideoJS you're using, or what other plugins you're using with it.

If you're able to reproduce the issue in an MVCE, post a comment here and the issue can be reopened.
