### ISSUE TITLE
Unable to import plugin in TypeScript project (stencil components)

### ISSUE THREAD

**Issue by maxpain84** [silvermine/videojs-quality-selector#55]
Hi, 

simple

import '@silvermine/videojs-quality-selector'; 

not working. I can not find that anything has been exported, how this plugin is intended to be used within typescript projects?

Thank you!

**Comment by clixmat** [comment]
I have the same problem

**Comment by yokuze** [comment]
The [README in this project says](https://github.com/silvermine/videojs-quality-selector#using-require):

> For videojs to use the plug-in, the plugin needs to register itself with the instance of videojs. This can be accomplished by:

```js
var videojs = require('videojs');

// The following registers the plugin with `videojs`
require('@silvermine/videojs-quality-selector')(videojs);
```

So you can't just import the plugin without doing anything with it. After you import it, you have to call the imported function and pass an instance of video.js.
