### ISSUE TITLE
Safari 264 Speed Up on Quality Change

### ISSUE THREAD

**Issue by cmshnrblu** [silvermine/videojs-quality-selector#58]
Hello,

I am not certain this is a quality-selector issue, but it may be. Does anyone working with safari playback have a solution to the "catch up" error that results occasionally when switching quality? On my player when I change from, say, 1080p to 4k, it seems as though the time starts ticking on playback even though the video isn't playing yet. Then it goes to what appears to be 1.5x speed or higher in order to "catch up" to the playback point. Are there any configuration changes that I can make to prevent this? Is there anything with quality-selector that I can modify to avoid this? Is there a way that I can prevent the time of playback from commencing until the video has loaded and is ready?

Many thanks, and sorry in advanced if this is not a quality-selector issue. I just do not know the origin of this issue to be perfectly honest.

**Comment by jthomerson** [comment]
Sorry, I haven't seen that issue. Since all we're doing is changing out the source, it couldn't really be related to this plugin. I'd suggest you open the issue on the VideoJS project.
