### ISSUE TITLE
Package depends on vulnerable versions of underscore 

### ISSUE THREAD

**Issue by zapalagrzegorz** [silvermine/videojs-quality-selector#72]
Hi,

I got message with npm audit that:
@silvermine/videojs-quality-selector *
Depends on vulnerable versions of underscore
node_modules/@silvermine/videojs-quality-selector

Can you bump up dependency underscore to to 1.12.1 or higher, which is unaffected by the vulnerability .

Thank you in advance.

**Comment by jthomerson** [comment]
See #73

**Comment by jthomerson** [comment]
Fixed in + @silvermine/videojs-quality-selector@1.2.5
