### ISSUE TITLE
Not working Properly

### ISSUE THREAD

**Issue by sajedulsakib001** [silvermine/videojs-quality-selector#75]
This plugin isn't working on mobile chorme browse. But in web viewer it's working...

**Comment by jthomerson** [comment]
You'd have to actually explain what's not working and give some details of what you've tried and how you're using it before we can take the issue seriously. It works for hundreds of thousands of our users on Chrome mobile.

**Comment by sajedulsakib001** [comment]
Thanks for your instant reply.

But can you help me please.

What i did wrong here, This is the player👇

https://github.com/sajedulsakib001/VideoJs/blob/main/player.html
