### ISSUE TITLE
select video base on network bandwith 

### ISSUE THREAD

**Issue by nadia-am** [silvermine/videojs-quality-selector#87]
add a feature to auto play video base on network bandwith on first play

**Comment by jthomerson** [comment]
HLS is best-suited for this, so we have no plans to add it.

**Comment by nadia-am** [comment]
@jthomerson where can i find a example of how to use it?

**Comment by jthomerson** [comment]
You just nee to Google "HLS video" or something similar. What examples you need all depend on which parts of it you are needing to implement.
