### ISSUE TITLE
`TypeError: n.extend is not a function` at the latest version .

### ISSUE THREAD

**Issue by magic-thomas** [silvermine/videojs-quality-selector#98]
Hello. 

cdn link is used. 

`/*! @silvermine/videojs-quality-selector 2023-03-21 v1.3.0 */`

it gives `lvermine-videojs-quality-selector.js:2061 Uncaught TypeError: n.extend is not a function` 

used  videojs version : 8.3.0

I guess the latest source code is rolled back.

**Comment by arulpatmose** [comment]
Any updated on this issue? Thanks

**Comment by gsimko** [comment]
Sent https://github.com/silvermine/videojs-quality-selector/pull/99

**Comment by fguillen** [comment]
Is this solved? duplicated?

**Comment by fguillen** [comment]
For now, the only solution I found is using VideoJS v7.21.5

**Comment by magic-thomas** [comment]
> For now, the only solution I found is using VideoJS v7.21.5

I agree. 

I downgraded video js to 7.x . it worked.

**Comment by gsimko** [comment]
A fix was merged already in
https://github.com/silvermine/videojs-quality-selector/pull/93#issuecomment-1725889902

**Comment by yokuze** [comment]
This is addressed in v1.3.1 of this plugin. Thanks!
